### ISSUE TITLE
White text appears in front of legends on dev.components

### ISSUE THREAD

**Issue by geistling** [geistling/components_bandcamp#28]
Chrome desktop. The text can obscure parts of the labels at various sizes.

![image](https://user-images.githubusercontent.com/34081638/102404076-0b2eda00-3f9c-11eb-8cc9-b386a4c1143c.png)

746x715:
![image](https://user-images.githubusercontent.com/34081638/102404256-46c9a400-3f9c-11eb-935c-9e6d2635a373.png)

**Comment by thely** [comment]
What a fun bug! This was actually an issue with the site, not bandcamp. It's fixed, though
